### ISSUE TITLE
Feature: Drive specific spindown

### ISSUE THREAD

**Issue by fightforlife** [desbma/hddfancontrol#41]
Hi desbma, 

currently the spindown time/option is valid for all monitored disks.
Would it be possible to change this?

- Either some kind of whitelist/blacklist approach, where you define which disks should spindown
- Or define spindown time per disk.

I think this feature would be helpful when you are using Snapraid. (for me) Since snipraid only needs the parity drives online when sync is done every few days. So the parity drive should spindown quickly after sync/scrub. But the data drives should be on longer, depending on your usage.

Best regards

**Comment by desbma** [comment]
I'm currently rewriting `hddfancontrol` in the [v2 branch](https://github.com/desbma/hddfancontrol/tree/v2).

The "auto drive spin-down" feature will be removed, because I think this is best implemented in a separate daemon, I recommend using [hd-idle](https://github.com/adelolmo/hd-idle) instead.

See also https://github.com/desbma/hddfancontrol/tree/v2?tab=readme-ov-file#migrating-from-v1x
